import type { GameMeta } from './types.js';
export const games: GameMeta[] = [
  {
    id: 'uno',
    name: 'UNO',
    subtitle: '一张逆转，全场沸腾',
    category: 'cards',
    minPlayers: 2,
    maxPlayers: 6,
    supportsAI: true,
    supportsMultiplayer: true,
    available: true,
    accent: '#e5a94e',
    tag: '人气之选',
    description: '颜色、数字、一点点运气。把最后一张牌打出去！',
    duration: '5–15 分钟',
  },
  {
    id: 'gomoku',
    name: '五子棋',
    subtitle: '方寸棋盘，步步为营',
    category: 'board',
    minPlayers: 2,
    maxPlayers: 2,
    supportsAI: true,
    supportsMultiplayer: true,
    available: false,
    accent: '#8faca0',
    tag: '经典棋类',
    description: '黑白之间的博弈，率先连成五子即获胜。',
    duration: '5–20 分钟',
  },
  {
    id: 'xiangqi',
    name: '中国象棋',
    subtitle: '楚河汉界，谁主沉浮',
    category: 'board',
    minPlayers: 2,
    maxPlayers: 2,
    supportsAI: true,
    supportsMultiplayer: true,
    available: false,
    accent: '#c59a80',
    tag: '国风策略',
    description: '调兵遣将，在楚河汉界之间寻找制胜的一步。',
    duration: '15–40 分钟',
  },
  {
    id: 'doudizhu',
    name: '斗地主',
    subtitle: '默契搭档，欢乐加倍',
    category: 'cards',
    minPlayers: 3,
    maxPlayers: 3,
    supportsAI: true,
    supportsMultiplayer: true,
    available: false,
    accent: '#afa0c9',
    tag: '欢乐组队',
    description: '三人一桌，经典的合作与对抗。',
    duration: '5–15 分钟',
  },
  {
    id: 'holdem',
    name: '德州扑克',
    subtitle: '读懂对手，掌控全局',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 6,
    supportsAI: true,
    supportsMultiplayer: true,
    available: false,
    accent: '#7aa3b6',
    tag: '策略竞技',
    description: '用筹码讲述你的故事。仅供休闲，无现金投注。',
    duration: '15–30 分钟',
  },
];
export const gameById = (id: string) => games.find((g) => g.id === id);
